Refactored code with optimisations

diff --git a/src/pacbuilder b/src/pacbuilder
--- a/src/pacbuilder
+++ b/src/pacbuilder
@@ -55,15 +55,15 @@ fhelp()
   local EXTRA_FLAG=$1
 
   if [ $(strncmp "${EXTRA_FLAG}" "-h" 2) = 0 ] || [ $(strncmp "${EXTRA_FLAG}" "--help" 6) = 0 ]; then
-    printf "usage:  ${PROJECT_NAME} {-B --build} [options] [package(s)]\n \
-      \roptions:\n \
-      \r  -u, --upgrade        clean and upgrade the contents of each package.\n \
-      \r      --clean          clean the contents of each given package.\n \
-      \r      --list           list the existing packages from the build directory\n \
-      \r                       or their contents, if provided name.\n \
-      \r      --edit           edit PKGBUILD before compiling.\n \
-      \r                       the modification will be stored as a patch file.\n \
-      \r"
+    printf "%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n"                                       \
+      "usage:  ${PROJECT_NAME} {-B --build} [options] [package(s)]"                 \
+      "options:"                                                                    \
+      "  -u, --upgrade        clean and upgrade the contents of each package."      \
+      "      --clean          clean the contents of each given package."            \
+      "      --list           list the existing packages from the build directory"  \
+      "                       or their contents, if provided name."                 \
+      "      --edit           edit PKGBUILD before compiling."                      \
+      "                       the modification will be stored as a patch file."
   else
     pacman --help | head -n 11 | sed "s/pacman/${PROJECT_NAME}/g"
     printf "    ${PROJECT_NAME} {-B --build}    [options] [package(s)]\n\n"
@@ -75,12 +75,13 @@ fhelp()
 
 fversion()
 {
-  printf "\r  .--.                  Pacbuilder v0.0.3\n \
-          \r / _.-' .-.  .-.  .-.   Copyright (C) 2025 SimplyCEO <simplyceo.developer@gmail.com>\n \
-          \r \\  '-. '-'  '-'  '-'\n \
-          \r  '--'\n \
-          \r                        This application may be freely redistributed under\n \
-          \r                        the terms of the Open Software License 3.0.\n"
+  printf "%s\n%s\n%s\n%s\n%s\n%s\n"                                                         \
+    "  .--.                  Pacbuilder v0.0.4"                                             \
+    " / _.-' .-.  .-.  .-.   Copyright (C) 2025 SimplyCEO <simplyceo.developer@gmail.com>"  \
+    " \\  '-. '-'  '-'  '-'"                                                                \
+    "  '--'"                                                                                \
+    "                        This application may be freely redistributed under"            \
+    "                        the terms of the Open Software License 3.0."
 
   return 0
 }
@@ -91,13 +92,13 @@ list_clone_directory()
   local SILENT=$2
 
   if [ ! -z $SILENT ] && [ $SILENT -eq 1 ]; then
-    if [ -z "${PACKAGE}" ]; then
+    if [ -z "${PACKAGE}" ] || [ "${PACKAGE}" = "NULL" ]; then
       if [ -d "${REPO_FOLDER}" ]; then return 0; else return 1; fi
     else
       if [ -d "${REPO_FOLDER}/${PACKAGE}" ]; then return 0; else return 1; fi
     fi
   else
-    if [ -z "${PACKAGE}" ]; then
+    if [ -z "${PACKAGE}" ] || [ "${PACKAGE}" = "NULL" ]; then
       ls "${REPO_FOLDER}"
     else
       ls "${REPO_FOLDER}/${PACKAGE}" 2>/dev/null
@@ -111,7 +112,7 @@ get_editor()
 {
   if [ -z $EDITOR ]; then
     local EDITOR_ARRAY="vim vi nano neovim ed"
-    for editor in ${EDITOR_ARRAY}; do
+    for editor in $(echo "${EDITOR_ARRAY}" | cut -d " " -f 1-500); do
       if which $editor >/dev/null 2>&1; then echo $editor; return 0; fi
     done
   else
@@ -152,7 +153,7 @@ clean_package()
 {
   local PACKAGE=$1
 
-  if [ ! -z "${PACKAGE}" ]; then
+  if [ "${PACKAGE}" != "NULL" ] && [ ! -z "${PACKAGE}" ]; then
     cd "${REPO_FOLDER}/${PACKAGE}"
     rm -rf src/*build*
     cd -
@@ -161,11 +162,11 @@ clean_package()
     DEFAULT_RESPONSE="n"
     read RESPONSE
     if [ -z "${RESPONSE}" ]; then RESPONSE="${DEFAULT_RESPONSE}"; fi
-    case "${RESPONSE}" in
-      N|n|no)
+    case $(char 1 $(echo "${RESPONSE}" | tr '[:upper:]' '[:lower:]')) in
+      n)
         exit 1
         ;;
-      Y|y|yes)
+      y)
         cd "${REPO_FOLDER}"
         for folder in $(/bin/ls); do
           rm -rf "${folder}"
@@ -189,8 +190,8 @@ clone_package()
   if [ ! -f "${REPO_FOLDER}/${PACKAGE}/PKGBUILD" ]; then
     printf "\033[1;34m::\033[0m \033[1mAttempting to download ${PACKAGE}...\033[0m\n"
 
-    for GITURL in "${REPOSITORIES}"; do
-      if [ ! -z "${GITURL}"]; then
+    for GITURL in $(echo "${REPOSITORIES}" | cut -d " " -f 1-500); do
+      if [ ! -z "${GITURL}" ]; then
         GIT_TERMINAL_PROMPT=0 git clone ${GITURL}/${PACKAGE}.git ${REPO_FOLDER}/${PACKAGE} >/dev/null 2>&1
       fi
     done
@@ -201,7 +202,7 @@ clone_package()
     fi
 
     printf "\033[1;32m::\033[0m \033[1m${PACKAGE} was succesfully downloaded. Building...\033[0m\n"
-    makepkg --printsrcinfo > .SRCINFO
+    if [ ! -f .SRCINFO ]; then makepkg --printsrcinfo > .SRCINFO; fi
   else
     printf "\033[1;34m::\033[0m \033[1m${PACKAGE} already exists. Building...\033[0m\n"
 
@@ -273,6 +274,50 @@ run_pacman()
   pacman $@
 }
 
+build_packages()
+{
+  clone_package "$1"
+  if [ $? -ne 1 ]; then
+    build_package "$1"
+    if [ $? -eq 0 ]; then
+      install_package "$1"
+    fi
+  fi
+  return 0
+}
+
+clean_packages()
+{
+  list_clone_directory $1 1
+  if [ $? -eq 0 ]; then
+    clean_package $1
+  fi
+  return 0
+}
+
+edit_packages()
+{
+  clone_package $1
+  if [ $? -ne 1 ]; then
+    edit_package $1
+    build_package $1
+    if [ $? -eq 0 ]; then
+      install_package $1
+    fi
+  fi
+  return 0
+}
+
+list_packages()
+{
+  list_clone_directory $1
+  if [ $? -ne 0 ]; then
+    printf "\033[1;31m::\033[0m \033[1mERROR: $1 package not found in clone directory.\n"
+    return 1
+  fi
+  return 0
+}
+
 upgrade_packages()
 {
   list_clone_directory "$1" 1
@@ -281,7 +326,9 @@ upgrade_packages()
     clone_package "$1" 1
     if [ $? -ne 1 ]; then
       build_package "$1"
-      if [ $? -eq 0 ]; then install_package "$1"; fi
+      if [ $? -eq 0 ]; then
+        install_package "$1"
+      fi
     fi
   fi
 }
@@ -301,37 +348,25 @@ case $(array 0 "${OPTIONS}") in
     case "${EXTRA_OPTION}" in
     --clean|--edit|--list|--upgrade)
       shift
-      EXTRA_PACKAGES="$1"
+      EXTRA_PACKAGES="$@"
       if [ ! -z "${EXTRA_PACKAGES}" ]; then
-        for package in "$@"; do
-          # List packages from clone directory.
-          if [ $(strncmp "${EXTRA_OPTION}" "--list" 6) = 0 ]; then
-            list_clone_directory "${package}"
-            if [ $? -ne 0 ]; then printf "\033[1;31m::\033[0m \033[1mERROR: ${package} package not found in clone directory.\n"; exit 1; fi
-          # Clean package directory.
-        elif [ $(strncmp "${EXTRA_OPTION}" "--clean" 7) = 0 ]; then
-            list_clone_directory "${package}" 1
-            if [ $? -eq 0 ]; then clean_package "${package}"; fi
-          elif [ $(strncmp "${EXTRA_OPTION}" "--edit" 6) = 0 ]; then
-            clone_package "${package}"
-            if [ $? -ne 1 ]; then
-              edit_package "${package}"
-              build_package "${package}"
-              if [ $? -eq 0 ]; then install_package "${package}"; fi
-            fi
-          elif [ $(strncmp "${EXTRA_OPTION}" "--upgrade" 9) = 0 ]; then
-            upgrade_packages "${package}"
-          fi
+        for package in $(echo "${EXTRA_PACKAGES}" | cut -d " " -f 1-500); do
+          case "${EXTRA_OPTION}" in
+            # List packages from clone directory.
+            --list) list_packages "${package}" ;;
+            # Clean package directory.
+            --clean) clean_packages "${package}" ;;
+            --edit) edit_packages "${package}" ;;
+            --upgrade) upgrade_packages "${package}" ;;
+          esac
         done
         exit 0
       fi
 
       # Clean packages directory.
-      if [ $(strncmp "${EXTRA_OPTION}" "--clean" 7) = 0 ]; then
-        list_clone_directory "" 1
-        if [ $? -eq 0 ]; then clean_package; fi
-        exit 0
-      fi
+      case "${EXTRA_OPTION}" in
+        --clean) clean_packages NULL; exit 0 ;;
+      esac
 
       list_clone_directory
       exit 0
@@ -351,16 +386,8 @@ esac
 if [ ! -z "${PACKAGES}" ]; then
   for PKG in "${PACKAGES}"; do
     case $(array 0 "${OPTIONS}") in
-      -B|--build)
-        clone_package "${PKG}"
-        if [ $? -ne 1 ]; then
-          build_package "${PKG}"
-          if [ $? -eq 0 ]; then install_package "${PKG}"; fi
-        fi
-        ;;
-      -Bu)
-        upgrade_packages "${PKG}"
-        ;;
+      -B|--build) build_packages "${PKG}" ;;
+      -Bu) upgrade_packages "${PKG}" ;;
     esac
   done
 fi
